spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://192.168.209.135:3306/test?useUnicode=true&characterEncoding=utf8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
mybatis:
  type-aliases-package: com.lfy.mvcdemo.bean
  # 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件
  mapper-locations: classpath\:mapper/*.xml